FROM hivesolutions/pypy:latest

LABEL version="1.0"
LABEL maintainer="Hive Solutions <development@hive.pt>"

EXPOSE 2525

VOLUME /data

ENV LEVEL=INFO
ENV HOST=0.0.0.0
ENV PORT=2525
ENV ROOT_DIR=/data
ENV SMTP_AUTH=memory
ENV SMTP_HOST=SMTP_HOST

WORKDIR /data

RUN pip install --upgrade netius logstash-api

RUN groupadd --system app && useradd --system --gid app app && \
    mkdir -p /data && chown -R app:app /data
USER app

CMD ["/usr/bin/python", "-m", "netius.extra.smtp_r"]
