FROM rust:latest AS builder

RUN apt-get update && apt-get install -y -q --no-install-recommends build-essential\
    curl clang cmake libglib2.0-dev lld protobuf-compiler &&\
    cargo install --root /tmp/deno --locked deno

FROM alpine:3.18

LABEL version="1.0"
LABEL maintainer="Hive Solutions <development@hive.pt>"

WORKDIR /usr/local/bin

COPY --from=builder /tmp/deno .

CMD ["deno --version"]
