FROM hivesolutions/ubuntu:xenial

LABEL version="1.0"
LABEL maintainer="Hive Solutions <development@hive.pt>"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update &&\
    apt-get install -y -q --no-install-recommends apt-transport-https sudo gcc make curl pypy linux-headers-generic\
    libssl-dev python-dev python3-dev pypy-dev &&\
    wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O /tmp/packages-microsoft-prod.deb &&\
    dpkg -i /tmp/packages-microsoft-prod.deb && apt update &&\
    apt-get -y -q --no-install-recommends install dotnet-runtime-6.0 aspnetcore-runtime-6.0 &&\
    rm -f /tmp/packages-microsoft-prod.deb && apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
