name: Build and Push QEMU RPi Image
on:
  push:
    branches-ignore:
      - none
    paths:
      - "qemu_rpi/**"
  workflow_dispatch:
jobs:
  build:
    name: Build
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set tag name based on branch
        id: set_tag
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            GITHUB_REFNAME=${{ github.ref_name }}
            BRANCH_NAME=${GITHUB_REFNAME//\//_}
            echo "tag=latest-$BRANCH_NAME" >> $GITHUB_OUTPUT
          fi
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "qemu_rpi"
          file: "qemu_rpi/Dockerfile"
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: hivesolutions/qemu_rpi:${{ steps.set_tag.outputs.tag }}
