name: Build and Push Python Images
on:
  push:
    branches-ignore:
      - none
    paths:
      - "python/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set tag name based on branch
        id: set_tag
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "::set-output name=tag::latest"
          else
            echo "::set-output name=tag::${{ github.ref_name }}"
          fi
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./python/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          push: true
          tags: hivesolutions/python:${{ steps.set_tag.outputs.tag }}
