name: Build and Push Proxy Images
on:
  push:
    branches-ignore:
      - none
    paths:
      - "proxy/**"
      - "proxy_d/**"
  workflow_dispatch:
jobs:
  build:
    name: Build
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        config:
          - { dockerfile: "proxy/ams-logic/Dockerfile", context: "proxy/ams-logic", image_name: "proxy_ams", tag_name: "latest" }
          - { dockerfile: "proxy/hive-logic/Dockerfile", context: "proxy/hive-logic", image_name: "proxy_hive", tag_name: "latest" }
          - { dockerfile: "proxy/hive-logic/Dockerfile.pypy", context: "proxy/hive-logic", image_name: "proxy_hive", tag_name: "pypy" }
          - { dockerfile: "proxy/ldj-logic/Dockerfile", context: "proxy/ldj-logic", image_name: "proxy_ldj", tag_name: "latest" }
          - { dockerfile: "proxy/lets-logic/Dockerfile", context: "proxy/lets-logic", image_name: "proxy_lets", tag_name: "latest" }
          - { dockerfile: "proxy/lets-logic/Dockerfile.pypy", context: "proxy/lets-logic", image_name: "proxy_lets", tag_name: "pypy" }
          - { dockerfile: "proxy/multi-logic/Dockerfile", context: "proxy/multi-logic", image_name: "proxy_multi", tag_name: "latest" }
          - { dockerfile: "proxy/multi-logic/Dockerfile.pypy", context: "proxy/multi-logic", image_name: "proxy_multi", tag_name: "pypy" }
          - { dockerfile: "proxy/nyc-logic/Dockerfile", context: "proxy/nyc-logic", image_name: "proxy_nyc", tag_name: "latest" }
          - { dockerfile: "proxy_d/Dockerfile", context: "proxy_d", image_name: "proxy_d", tag_name: "latest" }
          - { dockerfile: "proxy_d/Dockerfile.pypy", context: "proxy_d", image_name: "proxy_d", tag_name: "pypy" }
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set tag name based on branch
        id: set_tag
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "tag=${{ matrix.config.tag_name }}" >> $GITHUB_OUTPUT
          else
            GITHUB_REFNAME=${{ github.ref_name }}
            BRANCH_NAME=${GITHUB_REFNAME//\//_}
            echo "tag=${{ matrix.config.tag_name }}-$BRANCH_NAME" >> $GITHUB_OUTPUT
          fi
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.config.context }}
          file: ${{ matrix.config.dockerfile }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: hivesolutions/${{ matrix.config.image_name }}:${{ steps.set_tag.outputs.tag }}
